### ISSUE TITLE
Check stalkerware apps

### ISSUE THREAD

**Issue by Te-k** [Te-k/stalkerware-indicators#77]
https://www.santeplusmag.com/il-est-desormais-possible-despionner-vos-contacts-sur-whatsapp-pour-savoir-avec-qui-et-de-quoi-ils-parlent-ma-vie-au-quotidien-000015917/

https://www.santeplusmag.com/comment-espionner-un-telephone-legalement-ma-vie-au-quotidien-000015842/

**Comment by jvoisin** [comment]
- Whatsagent doesn't have any component on the victim side, but since it looks dead, I don't think we need to care about it anyway.
- mspy, we already have a ton of IOC for it
- cerberus, we already have a ton of IOC for it
- trackview, we already have a ton of IOC for it, but I added some more just in case in c6060f5cea30427d42831c77d10f2ebdcbbb97dd
- KasperskySafeKids, I added IOC in 6522077c5c3018e88b34c8a96d02d784045bae18
- KidsControl, I added IOC in c2b0edb17de74c41bae3d3d34c1fe26bc0184fc2
- FindMyKids, I added IOC in 8e0ae5cb2ad09acc4a03a6b9dcf7cbbe302cd360
